export default {
  response: {
    version: '0.1',
    termsofService: 'http://www.wunderground.com/weather/api/d/terms.html',
    features: {
      forecast: 1,
      geolookup: 1,
      conditions: 1,
      hourly: 1,
    },
  },
  location: {
    type: 'CITY',
    country: 'US',
    country_iso3166: 'US',
    country_name: 'USA',
    state: 'CO',
    city: 'Denver',
    tz_short: 'MDT',
    tz_long: 'America/Denver',
    lat: '39.74000168',
    lon: '-104.98000336',
    zip: '80201',
    magic: '1',
    wmo: '99999',
    l: '/q/zmw:80201.1.99999',
    requesturl: 'US/CO/Denver.html',
    wuiurl: 'https://www.wunderground.com/US/CO/Denver.html',
    nearby_weather_stations: {
      airport: {
        station: [
          {
            city: 'Aurora',
            state: 'CO',
            country: 'US',
            icao: 'KBKF',
            lat: '39.70000076',
            lon: '-104.75000000',
          },
          {
            city: 'Denver Centennial',
            state: 'CO',
            country: 'US',
            icao: 'KAPA',
            lat: '39.56999969',
            lon: '-104.84999847',
          },
          {
            city: 'Broomfield',
            state: 'CO',
            country: 'US',
            icao: 'KBJC',
            lat: '39.90999985',
            lon: '-105.12000275',
          },
          {
            city: 'Denver',
            state: 'CO',
            country: 'US',
            icao: 'KDEN',
            lat: '39.86000061',
            lon: '-104.66999817',
          },
        ],
      },
      pws: {
        station: [
          {
            neighborhood: 'Capitol Hill',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE145',
            lat: 39.739201,
            lon: -104.984703,
            distance_km: 0,
            distance_mi: 0,
          },
          {
            neighborhood: 'Capitol Hill',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE218',
            lat: 39.734711,
            lon: -104.977921,
            distance_km: 0,
            distance_mi: 0,
          },
          {
            neighborhood: 'San Rafael Neighborhood',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE131',
            lat: 39.751591,
            lon: -104.977402,
            distance_km: 1,
            distance_mi: 0,
          },
          {
            neighborhood: 'Cheesman Park',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE115',
            lat: 39.735161,
            lon: -104.962387,
            distance_km: 1,
            distance_mi: 0,
          },
          {
            neighborhood: 'Alamo Placita',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE194',
            lat: 39.724731,
            lon: -104.977036,
            distance_km: 1,
            distance_mi: 1,
          },
          {
            neighborhood: 'Ballpark',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE233',
            lat: 39.758705,
            lon: -104.998383,
            distance_km: 2,
            distance_mi: 1,
          },
          {
            neighborhood: 'South City Park',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE369',
            lat: 39.742111,
            lon: -104.948509,
            distance_km: 2,
            distance_mi: 1,
          },
          {
            neighborhood: 'Country Club',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE243',
            lat: 39.720005,
            lon: -104.959892,
            distance_km: 2,
            distance_mi: 1,
          },
          {
            neighborhood: 'Congress Park',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE271',
            lat: 39.735527,
            lon: -104.944565,
            distance_km: 3,
            distance_mi: 1,
          },
          {
            neighborhood: 'Baker',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE203',
            lat: 39.712112,
            lon: -104.989082,
            distance_km: 3,
            distance_mi: 1,
          },
          {
            neighborhood: 'Country Club',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE130',
            lat: 39.711746,
            lon: -104.968918,
            distance_km: 3,
            distance_mi: 1,
          },
          {
            neighborhood: 'Northwest',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE119',
            lat: 39.754841,
            lon: -105.014832,
            distance_km: 3,
            distance_mi: 2,
          },
          {
            neighborhood: 'East',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE134',
            lat: 39.720428,
            lon: -104.949074,
            distance_km: 3,
            distance_mi: 2,
          },
          {
            neighborhood: 'Wash Park West',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE236',
            lat: 39.70813,
            lon: -104.981133,
            distance_km: 3,
            distance_mi: 2,
          },
          {
            neighborhood: 'Hale',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE201',
            lat: 39.727577,
            lon: -104.936836,
            distance_km: 3,
            distance_mi: 2,
          },
          {
            neighborhood: 'Denver',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE298',
            lat: 39.753696,
            lon: -104.983299,
            distance_km: 1,
            distance_mi: 0,
          },
          {
            neighborhood: 'Denver',
            city: 'Westside Neighborhood',
            state: 'CO',
            country: 'US',
            id: 'KCOWESTS2',
            lat: 39.734562,
            lon: -105.0056,
            distance_km: 2,
            distance_mi: 1,
          },
          {
            neighborhood: 'Denver',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE301',
            lat: 39.742802,
            lon: -104.953377,
            distance_km: 2,
            distance_mi: 1,
          },
          {
            neighborhood: 'Denver',
            city: 'Denver',
            state: 'CO',
            country: 'US',
            id: 'KCODENVE309',
            lat: 39.715542,
            lon: -104.989639,
            distance_km: 2,
            distance_mi: 1,
          },
        ],
      },
    },
  },
  current_observation: {
    image: {
      url: 'http://icons.wxug.com/graphics/wu2/logo_130x80.png',
      title: 'Weather Underground',
      link: 'http://www.wunderground.com',
    },
    display_location: {
      full: 'Denver, CO',
      city: 'Denver',
      state: 'CO',
      state_name: 'Colorado',
      country: 'US',
      country_iso3166: 'US',
      zip: '80201',
      magic: '1',
      wmo: '99999',
      latitude: '39.74000168',
      longitude: '-104.98000336',
      elevation: '1598.1',
    },
    observation_location: {
      full: 'Capitol Hill, Denver, Colorado',
      city: 'Capitol Hill, Denver',
      state: 'Colorado',
      country: 'US',
      country_iso3166: 'US',
      latitude: '39.734711',
      longitude: '-104.977921',
      elevation: '5331 ft',
    },
    estimated: {},
    station_id: 'KCODENVE218',
    observation_time: 'Last Updated on September 13, 2:16 PM MDT',
    observation_time_rfc822: 'Wed, 13 Sep 2017 14:16:33 -0600',
    observation_epoch: '1505333793',
    local_time_rfc822: 'Wed, 13 Sep 2017 14:16:36 -0600',
    local_epoch: '1505333796',
    local_tz_short: 'MDT',
    local_tz_long: 'America/Denver',
    local_tz_offset: '-0600',
    weather: 'Overcast',
    temperature_string: '81.5 F (27.5 C)',
    temp_f: 81.5,
    temp_c: 27.5,
    relative_humidity: '23%',
    wind_string: 'Calm',
    wind_dir: 'NNW',
    wind_degrees: 342,
    wind_mph: 0.0,
    wind_gust_mph: 0,
    wind_kph: 0,
    wind_gust_kph: 0,
    pressure_mb: '1006',
    pressure_in: '29.72',
    pressure_trend: '0',
    dewpoint_string: '40 F (5 C)',
    dewpoint_f: 40,
    dewpoint_c: 5,
    heat_index_string: 'NA',
    heat_index_f: 'NA',
    heat_index_c: 'NA',
    windchill_string: 'NA',
    windchill_f: 'NA',
    windchill_c: 'NA',
    feelslike_string: '81.5 F (26 C)',
    feelslike_f: '81.5',
    feelslike_c: '26',
    visibility_mi: '10.0',
    visibility_km: '16.1',
    solarradiation: '83',
    UV: '1.0',
    precip_1hr_string: '0.00 in ( 0 mm)',
    precip_1hr_in: '0.00',
    precip_1hr_metric: ' 0',
    precip_today_string: '0.00 in (0 mm)',
    precip_today_in: '0.00',
    precip_today_metric: '0',
    icon: 'cloudy',
    icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
    forecast_url: 'http://www.wunderground.com/US/CO/Denver.html',
    history_url:
      'http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KCODENVE218',
    ob_url:
      'http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.734711,-104.977921',
    nowcast: '',
  },
  forecast: {
    txt_forecast: {
      date: '1:44 PM MDT',
      forecastday: [
        {
          period: 0,
          icon: 'cloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
          title: 'Wednesday',
          fcttext:
            'Cloudy skies. A stray shower or thunderstorm is possible. High 83F. Winds W at 10 to 20 mph.',
          fcttext_metric:
            'Cloudy. A stray shower or thunderstorm is possible. High 29C. Winds W at 15 to 25 km/h.',
          pop: '20',
        },
        {
          period: 1,
          icon: 'nt_partlycloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
          title: 'Wednesday Night',
          fcttext:
            'Partly cloudy skies. A stray shower or thunderstorm is possible. Low 61F. Winds SSW at 5 to 10 mph.',
          fcttext_metric:
            'A few clouds. A stray shower or thunderstorm is possible. Low 16C. Winds light and variable.',
          pop: '20',
        },
        {
          period: 2,
          icon: 'mostlycloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/mostlycloudy.gif',
          title: 'Thursday',
          fcttext:
            'Partly cloudy skies in the morning will give way to cloudy skies during the afternoon. A stray shower or thunderstorm is possible. High 87F. Winds SW at 10 to 15 mph.',
          fcttext_metric:
            'A mix of clouds and sun in the morning followed by cloudy skies during the afternoon. A stray shower or thunderstorm is possible. High near 30C. Winds SW at 15 to 25 km/h.',
          pop: '20',
        },
        {
          period: 3,
          icon: 'nt_partlycloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
          title: 'Thursday Night',
          fcttext:
            'Cloudy skies early will become partly cloudy later at night. A stray shower or thunderstorm is possible. Low 57F. Winds SW at 5 to 10 mph.',
          fcttext_metric:
            'A few clouds from time to time. A stray shower or thunderstorm is possible. Low 14C. Winds WSW at 10 to 15 km/h.',
          pop: '20',
        },
        {
          period: 4,
          icon: 'clear',
          icon_url: 'http://icons.wxug.com/i/c/k/clear.gif',
          title: 'Friday',
          fcttext: 'Sunshine. High 83F. Winds NW at 5 to 10 mph.',
          fcttext_metric:
            'Plentiful sunshine. High 28C. Winds NW at 10 to 15 km/h.',
          pop: '0',
        },
        {
          period: 5,
          icon: 'nt_partlycloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
          title: 'Friday Night',
          fcttext:
            'A few clouds from time to time. A stray shower or thunderstorm is possible. Low near 50F. Winds NNE at 10 to 15 mph.',
          fcttext_metric:
            'Partly cloudy. A stray shower or thunderstorm is possible. Low around 10C. Winds NNE at 15 to 25 km/h.',
          pop: '20',
        },
        {
          period: 6,
          icon: 'partlycloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
          title: 'Saturday',
          fcttext:
            'Partly cloudy skies. Slight chance of a rain shower. High 73F. Winds ENE at 10 to 15 mph.',
          fcttext_metric:
            'Partly cloudy skies. Slight chance of a rain shower. High 23C. Winds ENE at 15 to 25 km/h.',
          pop: '20',
        },
        {
          period: 7,
          icon: 'nt_partlycloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
          title: 'Saturday Night',
          fcttext:
            'Considerable clouds early. Some decrease in clouds late. Slight chance of a rain shower. Low 52F. Winds NE at 5 to 10 mph.',
          fcttext_metric:
            'Cloudy skies early, then partly cloudy after midnight. Slight chance of a rain shower. Low 11C. Winds NNE at 10 to 15 km/h.',
          pop: '20',
        },
      ],
    },
    simpleforecast: {
      forecastday: [
        {
          date: {
            epoch: '1505350800',
            pretty: '7:00 PM MDT on September 13, 2017',
            day: 13,
            month: 9,
            year: 2017,
            yday: 255,
            hour: 19,
            min: '00',
            sec: 0,
            isdst: '1',
            monthname: 'September',
            monthname_short: 'Sep',
            weekday_short: 'Wed',
            weekday: 'Wednesday',
            ampm: 'PM',
            tz_short: 'MDT',
            tz_long: 'America/Denver',
          },
          period: 1,
          high: {
            fahrenheit: '88',
            celsius: '31',
          },
          low: {
            fahrenheit: '61',
            celsius: '16',
          },
          conditions: 'Overcast',
          icon: 'cloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
          skyicon: '',
          pop: 20,
          qpf_allday: {
            in: 0.0,
            mm: 0,
          },
          qpf_day: {
            in: 0.0,
            mm: 0,
          },
          qpf_night: {
            in: 0.0,
            mm: 0,
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0,
          },
          snow_day: {
            in: 0.0,
            cm: 0.0,
          },
          snow_night: {
            in: 0.0,
            cm: 0.0,
          },
          maxwind: {
            mph: 20,
            kph: 32,
            dir: 'W',
            degrees: 277,
          },
          avewind: {
            mph: 13,
            kph: 21,
            dir: 'W',
            degrees: 277,
          },
          avehumidity: 30,
          maxhumidity: 41,
          minhumidity: 20,
        },
        {
          date: {
            epoch: '1505437200',
            pretty: '7:00 PM MDT on September 14, 2017',
            day: 14,
            month: 9,
            year: 2017,
            yday: 256,
            hour: 19,
            min: '00',
            sec: 0,
            isdst: '1',
            monthname: 'September',
            monthname_short: 'Sep',
            weekday_short: 'Thu',
            weekday: 'Thursday',
            ampm: 'PM',
            tz_short: 'MDT',
            tz_long: 'America/Denver',
          },
          period: 2,
          high: {
            fahrenheit: '87',
            celsius: '31',
          },
          low: {
            fahrenheit: '57',
            celsius: '14',
          },
          conditions: 'Mostly Cloudy',
          icon: 'mostlycloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/mostlycloudy.gif',
          skyicon: '',
          pop: 20,
          qpf_allday: {
            in: 0.0,
            mm: 0,
          },
          qpf_day: {
            in: 0.0,
            mm: 0,
          },
          qpf_night: {
            in: 0.0,
            mm: 0,
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0,
          },
          snow_day: {
            in: 0.0,
            cm: 0.0,
          },
          snow_night: {
            in: 0.0,
            cm: 0.0,
          },
          maxwind: {
            mph: 15,
            kph: 24,
            dir: 'SW',
            degrees: 219,
          },
          avewind: {
            mph: 12,
            kph: 19,
            dir: 'SW',
            degrees: 219,
          },
          avehumidity: 34,
          maxhumidity: 49,
          minhumidity: 17,
        },
        {
          date: {
            epoch: '1505523600',
            pretty: '7:00 PM MDT on September 15, 2017',
            day: 15,
            month: 9,
            year: 2017,
            yday: 257,
            hour: 19,
            min: '00',
            sec: 0,
            isdst: '1',
            monthname: 'September',
            monthname_short: 'Sep',
            weekday_short: 'Fri',
            weekday: 'Friday',
            ampm: 'PM',
            tz_short: 'MDT',
            tz_long: 'America/Denver',
          },
          period: 3,
          high: {
            fahrenheit: '83',
            celsius: '28',
          },
          low: {
            fahrenheit: '50',
            celsius: '10',
          },
          conditions: 'Clear',
          icon: 'clear',
          icon_url: 'http://icons.wxug.com/i/c/k/clear.gif',
          skyicon: '',
          pop: 0,
          qpf_allday: {
            in: 0.0,
            mm: 0,
          },
          qpf_day: {
            in: 0.0,
            mm: 0,
          },
          qpf_night: {
            in: 0.0,
            mm: 0,
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0,
          },
          snow_day: {
            in: 0.0,
            cm: 0.0,
          },
          snow_night: {
            in: 0.0,
            cm: 0.0,
          },
          maxwind: {
            mph: 10,
            kph: 16,
            dir: 'NW',
            degrees: 308,
          },
          avewind: {
            mph: 8,
            kph: 13,
            dir: 'NW',
            degrees: 308,
          },
          avehumidity: 36,
          maxhumidity: 57,
          minhumidity: 17,
        },
        {
          date: {
            epoch: '1505610000',
            pretty: '7:00 PM MDT on September 16, 2017',
            day: 16,
            month: 9,
            year: 2017,
            yday: 258,
            hour: 19,
            min: '00',
            sec: 0,
            isdst: '1',
            monthname: 'September',
            monthname_short: 'Sep',
            weekday_short: 'Sat',
            weekday: 'Saturday',
            ampm: 'PM',
            tz_short: 'MDT',
            tz_long: 'America/Denver',
          },
          period: 4,
          high: {
            fahrenheit: '73',
            celsius: '23',
          },
          low: {
            fahrenheit: '52',
            celsius: '11',
          },
          conditions: 'Partly Cloudy',
          icon: 'partlycloudy',
          icon_url: 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
          skyicon: '',
          pop: 20,
          qpf_allday: {
            in: 0.0,
            mm: 0,
          },
          qpf_day: {
            in: 0.0,
            mm: 0,
          },
          qpf_night: {
            in: 0.0,
            mm: 0,
          },
          snow_allday: {
            in: 0.0,
            cm: 0.0,
          },
          snow_day: {
            in: 0.0,
            cm: 0.0,
          },
          snow_night: {
            in: 0.0,
            cm: 0.0,
          },
          maxwind: {
            mph: 15,
            kph: 24,
            dir: 'ENE',
            degrees: 60,
          },
          avewind: {
            mph: 11,
            kph: 18,
            dir: 'ENE',
            degrees: 60,
          },
          avehumidity: 52,
          maxhumidity: 75,
          minhumidity: 33,
        },
      ],
    },
  },
  hourly_forecast: [
    {
      FCTTIME: {
        hour: '15',
        hour_padded: '15',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505336400',
        pretty: '3:00 PM MDT on September 13, 2017',
        civil: '3:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '84', metric: '29' },
      dewpoint: { english: '38', metric: '3' },
      condition: 'Overcast',
      icon: 'cloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
      fctcode: '4',
      sky: '90',
      wspd: { english: '11', metric: '18' },
      wdir: { dir: 'WSW', degrees: '237' },
      wx: 'Cloudy',
      uvi: '2',
      humidity: '20',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '84', metric: '29' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.65', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '16',
        hour_padded: '16',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505340000',
        pretty: '4:00 PM MDT on September 13, 2017',
        civil: '4:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '82', metric: '28' },
      dewpoint: { english: '41', metric: '5' },
      condition: 'Overcast',
      icon: 'cloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
      fctcode: '4',
      sky: '87',
      wspd: { english: '12', metric: '19' },
      wdir: { dir: 'W', degrees: '272' },
      wx: 'Cloudy',
      uvi: '2',
      humidity: '23',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '82', metric: '28' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.66', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '17',
        hour_padded: '17',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505343600',
        pretty: '5:00 PM MDT on September 13, 2017',
        civil: '5:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '79', metric: '26' },
      dewpoint: { english: '42', metric: '6' },
      condition: 'Overcast',
      icon: 'cloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
      fctcode: '4',
      sky: '86',
      wspd: { english: '13', metric: '21' },
      wdir: { dir: 'WNW', degrees: '290' },
      wx: 'Cloudy',
      uvi: '1',
      humidity: '27',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '79', metric: '26' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.67', metric: '1005' },
    },
    {
      FCTTIME: {
        hour: '18',
        hour_padded: '18',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505347200',
        pretty: '6:00 PM MDT on September 13, 2017',
        civil: '6:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '80', metric: '27' },
      dewpoint: { english: '41', metric: '5' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
      fctcode: '2',
      sky: '59',
      wspd: { english: '11', metric: '18' },
      wdir: { dir: 'WNW', degrees: '304' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '25',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '80', metric: '27' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.66', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '19',
        hour_padded: '19',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505350800',
        pretty: '7:00 PM MDT on September 13, 2017',
        civil: '7:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '77', metric: '25' },
      dewpoint: { english: '42', metric: '6' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
      fctcode: '2',
      sky: '41',
      wspd: { english: '6', metric: '10' },
      wdir: { dir: 'SW', degrees: '233' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '28',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '77', metric: '25' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.68', metric: '1005' },
    },
    {
      FCTTIME: {
        hour: '20',
        hour_padded: '20',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505354400',
        pretty: '8:00 PM MDT on September 13, 2017',
        civil: '8:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '75', metric: '24' },
      dewpoint: { english: '43', metric: '6' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '37',
      wspd: { english: '6', metric: '10' },
      wdir: { dir: 'SW', degrees: '215' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '32',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '75', metric: '24' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.7', metric: '1006' },
    },
    {
      FCTTIME: {
        hour: '21',
        hour_padded: '21',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505358000',
        pretty: '9:00 PM MDT on September 13, 2017',
        civil: '9:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '72', metric: '22' },
      dewpoint: { english: '44', metric: '7' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '37',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SSW', degrees: '204' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '36',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '72', metric: '22' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.71', metric: '1006' },
    },
    {
      FCTTIME: {
        hour: '22',
        hour_padded: '22',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505361600',
        pretty: '10:00 PM MDT on September 13, 2017',
        civil: '10:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '70', metric: '21' },
      dewpoint: { english: '44', metric: '7' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '35',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SSW', degrees: '209' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '39',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '70', metric: '21' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.71', metric: '1006' },
    },
    {
      FCTTIME: {
        hour: '23',
        hour_padded: '23',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '13',
        mday_padded: '13',
        yday: '255',
        isdst: '1',
        epoch: '1505365200',
        pretty: '11:00 PM MDT on September 13, 2017',
        civil: '11:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Wednesday',
        weekday_name_night: 'Wednesday Night',
        weekday_name_abbrev: 'Wed',
        weekday_name_unlang: 'Wednesday',
        weekday_name_night_unlang: 'Wednesday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '69', metric: '21' },
      dewpoint: { english: '44', metric: '7' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '32',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SW', degrees: '227' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '41',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '69', metric: '21' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.72', metric: '1006' },
    },
    {
      FCTTIME: {
        hour: '0',
        hour_padded: '00',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505368800',
        pretty: '12:00 AM MDT on September 14, 2017',
        civil: '12:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '68', metric: '20' },
      dewpoint: { english: '43', metric: '6' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '32',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SSW', degrees: '210' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '41',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '68', metric: '20' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.72', metric: '1006' },
    },
    {
      FCTTIME: {
        hour: '1',
        hour_padded: '01',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505372400',
        pretty: '1:00 AM MDT on September 14, 2017',
        civil: '1:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '67', metric: '19' },
      dewpoint: { english: '43', metric: '6' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '38',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SSW', degrees: '202' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '41',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '67', metric: '19' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.73', metric: '1007' },
    },
    {
      FCTTIME: {
        hour: '2',
        hour_padded: '02',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505376000',
        pretty: '2:00 AM MDT on September 14, 2017',
        civil: '2:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '66', metric: '19' },
      dewpoint: { english: '42', metric: '6' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '43',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SSW', degrees: '202' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '42',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '66', metric: '19' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.73', metric: '1007' },
    },
    {
      FCTTIME: {
        hour: '3',
        hour_padded: '03',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505379600',
        pretty: '3:00 AM MDT on September 14, 2017',
        civil: '3:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '65', metric: '18' },
      dewpoint: { english: '42', metric: '6' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '44',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SSW', degrees: '194' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '42',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '65', metric: '18' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.73', metric: '1007' },
    },
    {
      FCTTIME: {
        hour: '4',
        hour_padded: '04',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505383200',
        pretty: '4:00 AM MDT on September 14, 2017',
        civil: '4:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '64', metric: '18' },
      dewpoint: { english: '41', metric: '5' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '48',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'S', degrees: '190' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '42',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '64', metric: '18' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.73', metric: '1007' },
    },
    {
      FCTTIME: {
        hour: '5',
        hour_padded: '05',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505386800',
        pretty: '5:00 AM MDT on September 14, 2017',
        civil: '5:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '63', metric: '17' },
      dewpoint: { english: '40', metric: '4' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '48',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SSW', degrees: '193' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '43',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '63', metric: '17' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.74', metric: '1007' },
    },
    {
      FCTTIME: {
        hour: '6',
        hour_padded: '06',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505390400',
        pretty: '6:00 AM MDT on September 14, 2017',
        civil: '6:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '62', metric: '17' },
      dewpoint: { english: '40', metric: '4' },
      condition: 'Clear',
      icon: 'clear',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_clear.gif',
      fctcode: '1',
      sky: '19',
      wspd: { english: '4', metric: '6' },
      wdir: { dir: 'SSW', degrees: '212' },
      wx: 'Clear',
      uvi: '0',
      humidity: '44',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '62', metric: '17' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.75', metric: '1007' },
    },
    {
      FCTTIME: {
        hour: '7',
        hour_padded: '07',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505394000',
        pretty: '7:00 AM MDT on September 14, 2017',
        civil: '7:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '62', metric: '17' },
      dewpoint: { english: '39', metric: '4' },
      condition: 'Clear',
      icon: 'clear',
      icon_url: 'http://icons.wxug.com/i/c/k/clear.gif',
      fctcode: '1',
      sky: '18',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SW', degrees: '215' },
      wx: 'Sunny',
      uvi: '0',
      humidity: '43',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '62', metric: '17' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.76', metric: '1008' },
    },
    {
      FCTTIME: {
        hour: '8',
        hour_padded: '08',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505397600',
        pretty: '8:00 AM MDT on September 14, 2017',
        civil: '8:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '65', metric: '18' },
      dewpoint: { english: '40', metric: '4' },
      condition: 'Clear',
      icon: 'clear',
      icon_url: 'http://icons.wxug.com/i/c/k/clear.gif',
      fctcode: '1',
      sky: '15',
      wspd: { english: '4', metric: '6' },
      wdir: { dir: 'SW', degrees: '222' },
      wx: 'Sunny',
      uvi: '0',
      humidity: '39',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '65', metric: '18' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.77', metric: '1008' },
    },
    {
      FCTTIME: {
        hour: '9',
        hour_padded: '09',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505401200',
        pretty: '9:00 AM MDT on September 14, 2017',
        civil: '9:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '71', metric: '22' },
      dewpoint: { english: '39', metric: '4' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
      fctcode: '2',
      sky: '31',
      wspd: { english: '4', metric: '6' },
      wdir: { dir: 'SW', degrees: '224' },
      wx: 'Partly Cloudy',
      uvi: '2',
      humidity: '32',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '71', metric: '22' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.76', metric: '1008' },
    },
    {
      FCTTIME: {
        hour: '10',
        hour_padded: '10',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505404800',
        pretty: '10:00 AM MDT on September 14, 2017',
        civil: '10:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '76', metric: '24' },
      dewpoint: { english: '39', metric: '4' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
      fctcode: '2',
      sky: '38',
      wspd: { english: '4', metric: '6' },
      wdir: { dir: 'SSW', degrees: '209' },
      wx: 'Partly Cloudy',
      uvi: '3',
      humidity: '26',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '76', metric: '24' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.74', metric: '1007' },
    },
    {
      FCTTIME: {
        hour: '11',
        hour_padded: '11',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505408400',
        pretty: '11:00 AM MDT on September 14, 2017',
        civil: '11:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '80', metric: '27' },
      dewpoint: { english: '38', metric: '3' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
      fctcode: '2',
      sky: '42',
      wspd: { english: '4', metric: '6' },
      wdir: { dir: 'SSW', degrees: '213' },
      wx: 'Partly Cloudy',
      uvi: '5',
      humidity: '23',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '80', metric: '27' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.71', metric: '1006' },
    },
    {
      FCTTIME: {
        hour: '12',
        hour_padded: '12',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505412000',
        pretty: '12:00 PM MDT on September 14, 2017',
        civil: '12:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '83', metric: '28' },
      dewpoint: { english: '37', metric: '3' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/partlycloudy.gif',
      fctcode: '2',
      sky: '55',
      wspd: { english: '4', metric: '6' },
      wdir: { dir: 'E', degrees: '100' },
      wx: 'Partly Cloudy',
      uvi: '6',
      humidity: '20',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '83', metric: '28' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.68', metric: '1005' },
    },
    {
      FCTTIME: {
        hour: '13',
        hour_padded: '13',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505415600',
        pretty: '1:00 PM MDT on September 14, 2017',
        civil: '1:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '84', metric: '29' },
      dewpoint: { english: '36', metric: '2' },
      condition: 'Mostly Cloudy',
      icon: 'mostlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/mostlycloudy.gif',
      fctcode: '3',
      sky: '61',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'E', degrees: '92' },
      wx: 'Mostly Cloudy',
      uvi: '6',
      humidity: '18',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '84', metric: '29' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.66', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '14',
        hour_padded: '14',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505419200',
        pretty: '2:00 PM MDT on September 14, 2017',
        civil: '2:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '85', metric: '29' },
      dewpoint: { english: '36', metric: '2' },
      condition: 'Mostly Cloudy',
      icon: 'mostlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/mostlycloudy.gif',
      fctcode: '3',
      sky: '73',
      wspd: { english: '6', metric: '10' },
      wdir: { dir: 'SSW', degrees: '199' },
      wx: 'Mostly Cloudy',
      uvi: '5',
      humidity: '17',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '85', metric: '29' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.64', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '15',
        hour_padded: '15',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505422800',
        pretty: '3:00 PM MDT on September 14, 2017',
        civil: '3:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '83', metric: '28' },
      dewpoint: { english: '37', metric: '3' },
      condition: 'Mostly Cloudy',
      icon: 'mostlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/mostlycloudy.gif',
      fctcode: '3',
      sky: '76',
      wspd: { english: '9', metric: '14' },
      wdir: { dir: 'WSW', degrees: '241' },
      wx: 'Mostly Cloudy',
      uvi: '3',
      humidity: '20',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '83', metric: '28' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.61', metric: '1003' },
    },
    {
      FCTTIME: {
        hour: '16',
        hour_padded: '16',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505426400',
        pretty: '4:00 PM MDT on September 14, 2017',
        civil: '4:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '81', metric: '27' },
      dewpoint: { english: '40', metric: '4' },
      condition: 'Overcast',
      icon: 'cloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
      fctcode: '4',
      sky: '81',
      wspd: { english: '12', metric: '19' },
      wdir: { dir: 'W', degrees: '280' },
      wx: 'Cloudy',
      uvi: '2',
      humidity: '24',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '81', metric: '27' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.6', metric: '1002' },
    },
    {
      FCTTIME: {
        hour: '17',
        hour_padded: '17',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505430000',
        pretty: '5:00 PM MDT on September 14, 2017',
        civil: '5:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '79', metric: '26' },
      dewpoint: { english: '41', metric: '5' },
      condition: 'Overcast',
      icon: 'cloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
      fctcode: '4',
      sky: '82',
      wspd: { english: '10', metric: '16' },
      wdir: { dir: 'WSW', degrees: '255' },
      wx: 'Cloudy',
      uvi: '1',
      humidity: '26',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '79', metric: '26' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.62', metric: '1003' },
    },
    {
      FCTTIME: {
        hour: '18',
        hour_padded: '18',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505433600',
        pretty: '6:00 PM MDT on September 14, 2017',
        civil: '6:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '78', metric: '26' },
      dewpoint: { english: '41', metric: '5' },
      condition: 'Mostly Cloudy',
      icon: 'mostlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/mostlycloudy.gif',
      fctcode: '3',
      sky: '75',
      wspd: { english: '10', metric: '16' },
      wdir: { dir: 'WSW', degrees: '238' },
      wx: 'Mostly Cloudy',
      uvi: '0',
      humidity: '27',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '78', metric: '26' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.62', metric: '1003' },
    },
    {
      FCTTIME: {
        hour: '19',
        hour_padded: '19',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505437200',
        pretty: '7:00 PM MDT on September 14, 2017',
        civil: '7:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '74', metric: '23' },
      dewpoint: { english: '43', metric: '6' },
      condition: 'Overcast',
      icon: 'cloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/cloudy.gif',
      fctcode: '4',
      sky: '81',
      wspd: { english: '8', metric: '13' },
      wdir: { dir: 'WSW', degrees: '248' },
      wx: 'Cloudy',
      uvi: '0',
      humidity: '34',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '74', metric: '23' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.64', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '20',
        hour_padded: '20',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505440800',
        pretty: '8:00 PM MDT on September 14, 2017',
        civil: '8:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '71', metric: '22' },
      dewpoint: { english: '44', metric: '7' },
      condition: 'Overcast',
      icon: 'cloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_cloudy.gif',
      fctcode: '4',
      sky: '80',
      wspd: { english: '6', metric: '10' },
      wdir: { dir: 'NW', degrees: '325' },
      wx: 'Cloudy',
      uvi: '0',
      humidity: '39',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '71', metric: '22' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.65', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '21',
        hour_padded: '21',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505444400',
        pretty: '9:00 PM MDT on September 14, 2017',
        civil: '9:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '69', metric: '21' },
      dewpoint: { english: '46', metric: '8' },
      condition: 'Mostly Cloudy',
      icon: 'mostlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif',
      fctcode: '3',
      sky: '73',
      wspd: { english: '6', metric: '10' },
      wdir: { dir: 'S', degrees: '181' },
      wx: 'Mostly Cloudy',
      uvi: '0',
      humidity: '43',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '69', metric: '21' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.67', metric: '1005' },
    },
    {
      FCTTIME: {
        hour: '22',
        hour_padded: '22',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505448000',
        pretty: '10:00 PM MDT on September 14, 2017',
        civil: '10:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '67', metric: '19' },
      dewpoint: { english: '46', metric: '8' },
      condition: 'Mostly Cloudy',
      icon: 'mostlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif',
      fctcode: '3',
      sky: '69',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SW', degrees: '215' },
      wx: 'Mostly Cloudy',
      uvi: '0',
      humidity: '47',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '67', metric: '19' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.67', metric: '1005' },
    },
    {
      FCTTIME: {
        hour: '23',
        hour_padded: '23',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '14',
        mday_padded: '14',
        yday: '256',
        isdst: '1',
        epoch: '1505451600',
        pretty: '11:00 PM MDT on September 14, 2017',
        civil: '11:00 PM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Thursday',
        weekday_name_night: 'Thursday Night',
        weekday_name_abbrev: 'Thu',
        weekday_name_unlang: 'Thursday',
        weekday_name_night_unlang: 'Thursday Night',
        ampm: 'PM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '66', metric: '19' },
      dewpoint: { english: '46', metric: '8' },
      condition: 'Mostly Cloudy',
      icon: 'mostlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif',
      fctcode: '3',
      sky: '70',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SW', degrees: '223' },
      wx: 'Mostly Cloudy',
      uvi: '0',
      humidity: '49',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '66', metric: '19' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '15',
      mslp: { english: '29.67', metric: '1005' },
    },
    {
      FCTTIME: {
        hour: '0',
        hour_padded: '00',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '15',
        mday_padded: '15',
        yday: '257',
        isdst: '1',
        epoch: '1505455200',
        pretty: '12:00 AM MDT on September 15, 2017',
        civil: '12:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Friday',
        weekday_name_night: 'Friday Night',
        weekday_name_abbrev: 'Fri',
        weekday_name_unlang: 'Friday',
        weekday_name_night_unlang: 'Friday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '64', metric: '18' },
      dewpoint: { english: '46', metric: '8' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '42',
      wspd: { english: '4', metric: '6' },
      wdir: { dir: 'SW', degrees: '225' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '52',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '64', metric: '18' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.66', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '1',
        hour_padded: '01',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '15',
        mday_padded: '15',
        yday: '257',
        isdst: '1',
        epoch: '1505458800',
        pretty: '1:00 AM MDT on September 15, 2017',
        civil: '1:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Friday',
        weekday_name_night: 'Friday Night',
        weekday_name_abbrev: 'Fri',
        weekday_name_unlang: 'Friday',
        weekday_name_night_unlang: 'Friday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '63', metric: '17' },
      dewpoint: { english: '46', metric: '8' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '45',
      wspd: { english: '4', metric: '6' },
      wdir: { dir: 'SW', degrees: '217' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '54',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '63', metric: '17' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.65', metric: '1004' },
    },
    {
      FCTTIME: {
        hour: '2',
        hour_padded: '02',
        min: '00',
        min_unpadded: '0',
        sec: '0',
        year: '2017',
        mon: '9',
        mon_padded: '09',
        mon_abbrev: 'Sep',
        mday: '15',
        mday_padded: '15',
        yday: '257',
        isdst: '1',
        epoch: '1505462400',
        pretty: '2:00 AM MDT on September 15, 2017',
        civil: '2:00 AM',
        month_name: 'September',
        month_name_abbrev: 'Sep',
        weekday_name: 'Friday',
        weekday_name_night: 'Friday Night',
        weekday_name_abbrev: 'Fri',
        weekday_name_unlang: 'Friday',
        weekday_name_night_unlang: 'Friday Night',
        ampm: 'AM',
        tz: '',
        age: '',
        UTCDATE: '',
      },
      temp: { english: '62', metric: '17' },
      dewpoint: { english: '45', metric: '7' },
      condition: 'Partly Cloudy',
      icon: 'partlycloudy',
      icon_url: 'http://icons.wxug.com/i/c/k/nt_partlycloudy.gif',
      fctcode: '2',
      sky: '54',
      wspd: { english: '5', metric: '8' },
      wdir: { dir: 'SSW', degrees: '199' },
      wx: 'Partly Cloudy',
      uvi: '0',
      humidity: '55',
      windchill: { english: '-9999', metric: '-9999' },
      heatindex: { english: '-9999', metric: '-9999' },
      feelslike: { english: '62', metric: '17' },
      qpf: { english: '0.0', metric: '0' },
      snow: { english: '0.0', metric: '0' },
      pop: '0',
      mslp: { english: '29.64', metric: '1004' },
    },
  ],
};

// let keys = Object.keys(data)
//
// let forecast = keys.map((day) => {
//   return data.forecast.forecastday
// })
// return forecast


console.log(data.location.city);
// console.log(data.location.state);
// console.log(data.forecast.forecastday);
